### ISSUE TITLE
Getting an HTTP 429 while using `.toDataURL`

### ISSUE THREAD

**Issue by williswcy** [typpo/chartjs-to-image#19]
I'm having trouble with creating some charts using this library.

I've written a function which maps a user to 2 different doughnut charts. I've ~50 users in the system.

When the environment is using HTTP, the charts are created correctly, but in HTTPS I keep getting HTTP 429. Any advice on how to solve this?

**Comment by typpo** [comment]
Hi @williswcy, can you give me an example chart that is producing a 429?  Are you loading more than 60 charts in rapid succession?

**Comment by williswcy** [comment]
To the second question: yes. I'm loading about 100 if I'm not mistaken. I presume I'm rate limited, right?


If I break these requests into different batches (right now I just put all of them into a Promise.all) it should have prevented the limitation, right?

**Comment by typpo** [comment]
Yeah, if you spread them out over more than 1 minute you should be good!

**Comment by williswcy** [comment]
Great! Will try tomorrow! Thank you very much!
