### ISSUE TITLE
Laravel implementation

### ISSUE THREAD

**Issue by Skadie86** [typpo/chartjs-to-image#20]
Hi,
i have very big issues to implement chart js to image in my laravel application.
did you have a instuction to do this? 
i would render my Chart and then save to my public folder to use it later to render a pdf file.
But if i try to load it in my project i have alway a error with the two line:
const fs = require('fs');
const axios = require('axios');

Uncaught ReferenceError: require is not defined 

thank you for your help

**Comment by typpo** [comment]
It sounds like maybe you're trying to use this in the browser?  If so, I would recommend using https://github.com/typpo/quickchart-js which has browser support.  Here's an example of its use on a webpage:

https://github.com/typpo/quickchart-js/blob/master/examples/browser.html
