### ISSUE TITLE
Support stepSize? couldn't figure out how to add steps on the radar type of chart.

### ISSUE THREAD

**Issue by rupertbulquerin** [typpo/chartjs-to-image#22]
Result from ChartJs
![Screen Shot 2022-11-18 at 4 59 06 PM](https://user-images.githubusercontent.com/37164890/202662583-8ba8b3fe-87c8-4d20-b819-72f59b5cc040.png)

Result using chartjs-to-image with same config
![chart](https://user-images.githubusercontent.com/37164890/202662688-8db341a3-f957-484d-8376-ed710ffe19e1.png)

expected result:
step size should be 1,2,3,4,5. not 2.xx, 2.xx, 2.xx, 3.xx, 3.xx .....

**Comment by typpo** [comment]
Hi @rupertbulquerin, can you provide a full chart config?  Step size is supported, so it means there's something wrong with the config, or you are not setting the correct Chart.js version.

**Comment by rupertbulquerin** [comment]
Hi @typpo, thanks for your reply. I'm using this config for both examples above with minimal changes to the background colors.

```
const data = {
    labels: userdataset.labels,
    datasets: [{
      label: chartname,
      data: userdataset.scores,
      fill: true,
      backgroundColor: '#407CCE54',
    }]
  };

  const elementsFormat = {
    line: {
      borderWidth: 3
    },
    point: {
      radius: 5,
      hoverRadius: 10,
      backgroundColor: 'white',
      borderColor: 'rgb(64, 124, 206)',
      borderWidth: 2
    },
  };

  const pluginsFormat = {
    legend: {
      display: false
    },   
    title: {
      display: false,
      text: chartname,
      color: '#111',
      font: {
        size: 16,
        family: 'nuninto'
      }
    },
  };

  const scalesFormat = {
    r: {
      suggestedMin: 0,
      suggestedMax: 5,
      angleLines: {
        color: '#fff'
      },  
      grid: {
        color: '#fff'
      },
      pointLabels: {
        color: 'black',
        font: {
          size: '13'
        }
      },
      ticks: {
        backdropColor: '#231F29',
        color: 'white'
      }
    } 
  };

  const config = {
    type: 'radar',
    data: data,
    options: {
      responsive: true,
      maintainAspectRatio: false,
      borderColor: 'rgba(200, 200, 200, 0.05)',
      labels: {
        font: {
          size: 14,
          family: 'nunito'
        },
      },
      elements: elementsFormat,
      scales: scalesFormat,
      plugins: pluginsFormat
    },
  };
```

**Comment by typpo** [comment]
It looks like this chart requires Chart.js version >= 3.  I've release 1.1.0 of this library, which adds `chart.setChartJsVersion`.  You can use to set the appropriate Chart.js version:
```js
chart.setChartJsVersion('3')
```

Please update and give it a try!

**Comment by rupertbulquerin** [comment]
Hi @typpo, it works now. Thank you for this update!
