### ISSUE TITLE
Remove legend

### ISSUE THREAD

**Issue by SergeySypalo** [typpo/chartjs-to-image#23]
Hi Typpo, thx for the excellent lib,
I used it to generate charts, but it still generates a legend, even when I set it to false in the config.
So when I generated an image on the client everything was ok, but using this lib it still displays the legend
Here are my line chart options:
```
const options = {
	elements: {
		point: { radius: 0 }
	},
	responsive: true,
	plugins: {
		legend: {
			display: false
		}
	}
}
```

**Comment by typpo** [comment]
Make sure you set your Chart.js version to v3+:

```
chart.setChartJsVersion("3.9.1")
```

(if you do not have `setChartJsVersion`, upgrade to version 1.1.0 of this library)

**Comment by SergeySypalo** [comment]
Thanks typpo, I was using the latest 1.1.0, but missing chart.setChartJsVersion("3.9.1") part.
Once added it, charts genereated as expected.
