### ISSUE TITLE
Add ChartJS 4 support

### ISSUE THREAD

**Issue by SergeySypalo** [typpo/chartjs-to-image#25]
Hi Typpo,
Please add ChartJS 4 support, as I tried to add chart.setChartJsVersion("4"), similarly to what you suggested in https://github.com/typpo/chartjs-to-image/issues/23 but still see the legend.

**Comment by typpo** [comment]
Hi @SergeySypalo, Chart.js v4 support has been added in both the self-hosted and managed versions.
https://github.com/typpo/quickchart/pull/145

**Comment by SergeySypalo** [comment]
Hi Typpo, I just re-generated the price charts using `.setChartJsVersion("4")` and still see a legend, tried to remove this part at and got the same result with the legend. Ideally would be to switch the default version to 4 and fix this issue to avoid the need to specify the latest version. It is ok to have this option for those who need previous versions but IMHO default should be 4.

**Comment by typpo** [comment]
My hunch is that maybe you're not using a version of the software that has the above update?  As a fallback, you can also try setting the version to 3 and see if there's a difference, as there is nothing changed in legend behavior between 3 and 4.

**Comment by SergeySypalo** [comment]
I'm always using the latest version of the software but had to fall back to version 3, which generated charts as expected, while using version 4 still keeps the legend, even when specified to don't.

**Comment by typpo** [comment]
Hi @SergeySypalo, we identified a potential issue on the backend and pushed out a fix.  Could you give it another try with v4?  Note that previously generated charts may be cached.

If you're still having trouble, please share an example chart that is not rendering properly on v4 :)

**Comment by SergeySypalo** [comment]
Thanks, Typpo, all good now, no legend as expected).
Would be nice to switch to v4 as a default to eliminate the need to specify the (anyway latest) version, and just keep this option for anyone who needs the previous version.
