### ISSUE TITLE
Add Types

### ISSUE THREAD

**Issue by antoinekm** [typpo/chartjs-to-image#28]
Hi, can you please add the Types, for those who use TypeScript 😄

**Comment by typpo** [comment]
Hi @AntoineKM,

I recommend using https://github.com/typpo/quickchart-js if you need types.  It's the same underlying library, just with more features, and it has Typescript support.

**Comment by antoinekm** [comment]
Hey, ty, just in case i've done a pull request with the types in #29 !

**Comment by antoinekm** [comment]
But it is sure that the types of [quickchart-js](https://github.com/typpo/quickchart-js) are much better

**Comment by typpo** [comment]
Thank you, @AntoineKM!  This is published on npm as version 1.2.0.
