### ISSUE TITLE
Usage is broken on electron's renderer.

### ISSUE THREAD

**Issue by rzfzr** [typpo/chartjs-to-image#40]
I get uncaughts `axios.post is not a function` at every function call.
I imagine it can be a matter of implementing something like this: https://github.com/axios/axios/issues/552#issuecomment-262884004

Will check it out soon.

**Comment by rzfzr** [comment]
I'm not too sure if it that is actually the case, I tried running on background and got the same issue...

edit, changing the import to:
```
const axios = require('axios/dist/node/axios.cjs'); // node commonJS bundle (ES2017)
```
gave me ` Error: certificate has expired` 

Tried disabling certificates [with this](https://stackoverflow.com/questions/54903199/how-to-ignore-ssl-certificate-validation-in-node-requests)

Then I got the following error and gave up using the lib:

```
Error occurred in handler for 'getChart': TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received an instance of Array
    at Object.openSync (fs.js:468:10)
    at Object.func [as openSync] (electron/js2c/asar_bundle.js:5:1846)
    at Object.writeFileSync (fs.js:1467:35)
    at ChartJsImage.toFile (webpack:///./node_modules/chartjs-to-image/index.js?:160:8)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async eval (webpack:///./src/background.ts?:38:5)
    at async electron/js2c/browser_init.js:197:563 {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

**Comment by typpo** [comment]
Try using [`quickchart-js`](https://github.com/typpo/quickchart-js/) instead.  It's the same API, except with browser support (which needed by electron)

**Comment by rzfzr** [comment]
Looks good, thanks for the tip.
(although from electron's background process shouldn't need browser support, from my understanding)
