### ISSUE TITLE
Cannot show title

### ISSUE THREAD

**Issue by wanghwh** [typpo/chartjs-to-image#41]
title cannot show in image 

here is my config:

```
const cfg = {
        type: "bar",
        data:  {
            labels: labels,
            datasets:[{
                label: "userNumber",
                data: datasets1

            }]
        },
           
        options: {
            plugins: {
                title:{
                    display: true,
                    text: "this is title"
                }
            }
        }

    };
```

**Comment by typpo** [comment]
Did you set the [chart.js version](https://github.com/typpo/chartjs-to-image?tab=readme-ov-file#setchartjsversionversion-string) to 3?  The default version is 2, but `options.plugins.title` is supported in v3.

**Comment by wanghwh** [comment]
thanks @typpo , it works if I set version to "3" or "4",  I don't realize chartjs-to-image is not applying latest version
