### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: Request failed with status code 400

### ISSUE THREAD

**Issue by srisai96** [typpo/chartjs-to-image#8]
(node:1308) UnhandledPromiseRejectionWarning: Error: Request failed with status code 400
    at createError (C:\pr\Saaradhi\node_modules\axios\lib\core\createError.js:16:15)
    at settle (C:\pr\Saaradhi\node_modules\axios\lib\core\settle.js:17:12)
    at IncomingMessage.handleStreamEnd (C:\pr\Saaradhi\node_modules\axios\lib\adapters\http.js:260:11)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1308) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:1308) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by typpo** [comment]
I need more context here.  What chart were you trying to create?  What operation did you call to cause this error?

**Comment by srisai96** [comment]
yeah, I'll provide the details. Is there any limitation on the amount of data that the library can handle?

**Comment by typpo** [comment]
It looks like you're generating an image for download, so the max request size would be about 10 MB.  Unfortunately the library doesn't do a great job of passing along error messages.  You can try your chart in the [Quickchart sandbox](https://quickchart.io/sandbox) to get an error message.

**Comment by srisai96** [comment]
Yes, I'm trying to generate an image. And I have a huge amount of data to be plotted on the graph. Could you please help me achieve it?

**Comment by typpo** [comment]
Resolved offline
