### ISSUE TITLE
Is there a way to get the chart image with tooltips shown?

### ISSUE THREAD

**Issue by michaelparkadze** [typpo/chartjs-to-image#9]
Hi, I am using this package on my nodejs service and I am very happy with it so far, now I am just wondering, is there an option to get the tooltips shown in the image? I need to show the chart with the exact numbers for each data in the chart (for example: bar chart).

I saw people on stackoverflow do it but with the regular package and I think those solution wont work for me. anyways thanks in advance.

**Comment by typpo** [comment]
It sounds like you are looking for [data labels](https://chartjs-plugin-datalabels.netlify.app/guide/).  This plugin is built into the library, you just have to enable it.  Check out the docs to customize the data labels.

Here's an example ([link](https://quickchart.io/sandbox/#%7B%0A%20%20type%3A%20'line'%2C%0A%20%20data%3A%20%7B%0A%20%20%20%20labels%3A%20%5B'January'%2C%20'February'%2C%20'March'%2C%20'April'%2C%20'May'%2C%20'June'%2C%20'July'%5D%2C%0A%20%20%20%20datasets%3A%20%5B%0A%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20label%3A%20'Dataset%201'%2C%0A%20%20%20%20%20%20%20%20backgroundColor%3A%20'rgba(255%2C%2099%2C%20132%2C%200.5)'%2C%0A%20%20%20%20%20%20%20%20borderColor%3A%20'rgb(255%2C%2099%2C%20132)'%2C%0A%20%20%20%20%20%20%20%20borderWidth%3A%201%2C%0A%20%20%20%20%20%20%20%20data%3A%20%5B-31%2C%20-70%2C%20-30%2C%20-33%2C%20-9%2C%2014%2C%20-41%5D%2C%0A%20%20%20%20%20%20%20%20fill%3A%20false%2C%0A%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20label%3A%20'Dataset%202'%2C%0A%20%20%20%20%20%20%20%20backgroundColor%3A%20'rgba(54%2C%20162%2C%20235%2C%200.5)'%2C%0A%20%20%20%20%20%20%20%20borderColor%3A%20'rgb(54%2C%20162%2C%20235)'%2C%0A%20%20%20%20%20%20%20%20borderWidth%3A%201%2C%0A%20%20%20%20%20%20%20%20data%3A%20%5B73%2C%2041%2C%2029%2C%2061%2C%20-65%2C%2059%2C%2038%5D%2C%0A%20%20%20%20%20%20%20%20fill%3A%20false%2C%0A%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%5D%2C%0A%20%20%7D%2C%0A%20%20options%3A%20%7B%0A%20%20%20%20title%3A%20%7B%0A%20%20%20%20%20%20display%3A%20true%2C%0A%20%20%20%20%20%20text%3A%20'Bar%20Chart'%2C%0A%20%20%20%20%7D%2C%0A%20%20%20%20plugins%3A%20%7B%0A%20%20%20%20%20%20datalabels%3A%20%7B%0A%20%20%20%20%20%20%20%20anchor%3A%20'center'%2C%0A%20%20%20%20%20%20%20%20align%3A%20'top'%2C%0A%20%20%20%20%20%20%20%20color%3A%20'%23666'%2C%0A%20%20%20%20%20%20%20%20font%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20weight%3A%20'normal'%2C%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%7D%2C%0A%20%20%7D%2C%0A%7D%0A))
![image](https://user-images.githubusercontent.com/310310/125651109-2fdfd659-d168-4b61-a5e2-e5c3bb0bb141.png)
